version: '3.8'

services:
  db:
    build:
      context: ./db
      cache_from:
        - "${DB_IMAGE}"
    image: "${DB_IMAGE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres_data: